// Copyright 2025 The GoGPU Authors
// SPDX-License-Identifier: MIT

//go:build windows

package d3d12

// D3D_FEATURE_LEVEL specifies the Direct3D feature level.
type D3D_FEATURE_LEVEL uint32

// Feature level constants.
const (
	D3D_FEATURE_LEVEL_1_0_CORE D3D_FEATURE_LEVEL = 0x1000
	D3D_FEATURE_LEVEL_9_1      D3D_FEATURE_LEVEL = 0x9100
	D3D_FEATURE_LEVEL_9_2      D3D_FEATURE_LEVEL = 0x9200
	D3D_FEATURE_LEVEL_9_3      D3D_FEATURE_LEVEL = 0x9300
	D3D_FEATURE_LEVEL_10_0     D3D_FEATURE_LEVEL = 0xa000
	D3D_FEATURE_LEVEL_10_1     D3D_FEATURE_LEVEL = 0xa100
	D3D_FEATURE_LEVEL_11_0     D3D_FEATURE_LEVEL = 0xb000
	D3D_FEATURE_LEVEL_11_1     D3D_FEATURE_LEVEL = 0xb100
	D3D_FEATURE_LEVEL_12_0     D3D_FEATURE_LEVEL = 0xc000
	D3D_FEATURE_LEVEL_12_1     D3D_FEATURE_LEVEL = 0xc100
	D3D_FEATURE_LEVEL_12_2     D3D_FEATURE_LEVEL = 0xc200
)

// D3D_SHADER_MODEL specifies the shader model version.
type D3D_SHADER_MODEL uint32

// Shader model constants.
const (
	D3D_SHADER_MODEL_5_1 D3D_SHADER_MODEL = 0x51
	D3D_SHADER_MODEL_6_0 D3D_SHADER_MODEL = 0x60
	D3D_SHADER_MODEL_6_1 D3D_SHADER_MODEL = 0x61
	D3D_SHADER_MODEL_6_2 D3D_SHADER_MODEL = 0x62
	D3D_SHADER_MODEL_6_3 D3D_SHADER_MODEL = 0x63
	D3D_SHADER_MODEL_6_4 D3D_SHADER_MODEL = 0x64
	D3D_SHADER_MODEL_6_5 D3D_SHADER_MODEL = 0x65
	D3D_SHADER_MODEL_6_6 D3D_SHADER_MODEL = 0x66
	D3D_SHADER_MODEL_6_7 D3D_SHADER_MODEL = 0x67
)

// D3D12_COMMAND_LIST_TYPE specifies the type of command list.
type D3D12_COMMAND_LIST_TYPE uint32

// Command list type constants.
const (
	D3D12_COMMAND_LIST_TYPE_DIRECT        D3D12_COMMAND_LIST_TYPE = 0
	D3D12_COMMAND_LIST_TYPE_BUNDLE        D3D12_COMMAND_LIST_TYPE = 1
	D3D12_COMMAND_LIST_TYPE_COMPUTE       D3D12_COMMAND_LIST_TYPE = 2
	D3D12_COMMAND_LIST_TYPE_COPY          D3D12_COMMAND_LIST_TYPE = 3
	D3D12_COMMAND_LIST_TYPE_VIDEO_DECODE  D3D12_COMMAND_LIST_TYPE = 4
	D3D12_COMMAND_LIST_TYPE_VIDEO_PROCESS D3D12_COMMAND_LIST_TYPE = 5
	D3D12_COMMAND_LIST_TYPE_VIDEO_ENCODE  D3D12_COMMAND_LIST_TYPE = 6
)

// D3D12_COMMAND_QUEUE_FLAGS specifies command queue flags.
type D3D12_COMMAND_QUEUE_FLAGS uint32

// Command queue flag constants.
const (
	D3D12_COMMAND_QUEUE_FLAG_NONE                D3D12_COMMAND_QUEUE_FLAGS = 0
	D3D12_COMMAND_QUEUE_FLAG_DISABLE_GPU_TIMEOUT D3D12_COMMAND_QUEUE_FLAGS = 1
)

// D3D12_COMMAND_QUEUE_PRIORITY specifies the priority level for a command queue.
type D3D12_COMMAND_QUEUE_PRIORITY int32

// Command queue priority constants.
const (
	D3D12_COMMAND_QUEUE_PRIORITY_NORMAL          D3D12_COMMAND_QUEUE_PRIORITY = 0
	D3D12_COMMAND_QUEUE_PRIORITY_HIGH            D3D12_COMMAND_QUEUE_PRIORITY = 100
	D3D12_COMMAND_QUEUE_PRIORITY_GLOBAL_REALTIME D3D12_COMMAND_QUEUE_PRIORITY = 10000
)

// D3D12_HEAP_TYPE specifies the type of heap.
type D3D12_HEAP_TYPE uint32

// Heap type constants.
const (
	D3D12_HEAP_TYPE_DEFAULT  D3D12_HEAP_TYPE = 1
	D3D12_HEAP_TYPE_UPLOAD   D3D12_HEAP_TYPE = 2
	D3D12_HEAP_TYPE_READBACK D3D12_HEAP_TYPE = 3
	D3D12_HEAP_TYPE_CUSTOM   D3D12_HEAP_TYPE = 4
)

// D3D12_CPU_PAGE_PROPERTY specifies the CPU-page properties for the heap.
type D3D12_CPU_PAGE_PROPERTY uint32

// CPU page property constants.
const (
	D3D12_CPU_PAGE_PROPERTY_UNKNOWN       D3D12_CPU_PAGE_PROPERTY = 0
	D3D12_CPU_PAGE_PROPERTY_NOT_AVAILABLE D3D12_CPU_PAGE_PROPERTY = 1
	D3D12_CPU_PAGE_PROPERTY_WRITE_COMBINE D3D12_CPU_PAGE_PROPERTY = 2
	D3D12_CPU_PAGE_PROPERTY_WRITE_BACK    D3D12_CPU_PAGE_PROPERTY = 3
)

// D3D12_MEMORY_POOL specifies the memory pool for the heap.
type D3D12_MEMORY_POOL uint32

// Memory pool constants.
const (
	D3D12_MEMORY_POOL_UNKNOWN D3D12_MEMORY_POOL = 0
	D3D12_MEMORY_POOL_L0      D3D12_MEMORY_POOL = 1
	D3D12_MEMORY_POOL_L1      D3D12_MEMORY_POOL = 2
)

// D3D12_HEAP_FLAGS specifies heap options.
type D3D12_HEAP_FLAGS uint32

// Heap flag constants.
const (
	D3D12_HEAP_FLAG_NONE                           D3D12_HEAP_FLAGS = 0
	D3D12_HEAP_FLAG_SHARED                         D3D12_HEAP_FLAGS = 1
	D3D12_HEAP_FLAG_DENY_BUFFERS                   D3D12_HEAP_FLAGS = 4
	D3D12_HEAP_FLAG_ALLOW_DISPLAY                  D3D12_HEAP_FLAGS = 8
	D3D12_HEAP_FLAG_SHARED_CROSS_ADAPTER           D3D12_HEAP_FLAGS = 32
	D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES            D3D12_HEAP_FLAGS = 64
	D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES        D3D12_HEAP_FLAGS = 128
	D3D12_HEAP_FLAG_HARDWARE_PROTECTED             D3D12_HEAP_FLAGS = 256
	D3D12_HEAP_FLAG_ALLOW_WRITE_WATCH              D3D12_HEAP_FLAGS = 512
	D3D12_HEAP_FLAG_ALLOW_SHADER_ATOMICS           D3D12_HEAP_FLAGS = 1024
	D3D12_HEAP_FLAG_CREATE_NOT_RESIDENT            D3D12_HEAP_FLAGS = 2048
	D3D12_HEAP_FLAG_CREATE_NOT_ZEROED              D3D12_HEAP_FLAGS = 4096
	D3D12_HEAP_FLAG_ALLOW_ALL_BUFFERS_AND_TEXTURES D3D12_HEAP_FLAGS = 0
	D3D12_HEAP_FLAG_ALLOW_ONLY_BUFFERS             D3D12_HEAP_FLAGS = 192
	D3D12_HEAP_FLAG_ALLOW_ONLY_NON_RT_DS_TEXTURES  D3D12_HEAP_FLAGS = 68
	D3D12_HEAP_FLAG_ALLOW_ONLY_RT_DS_TEXTURES      D3D12_HEAP_FLAGS = 132
)

// D3D12_RESOURCE_DIMENSION specifies the dimension of a resource.
type D3D12_RESOURCE_DIMENSION uint32

// Resource dimension constants.
const (
	D3D12_RESOURCE_DIMENSION_UNKNOWN   D3D12_RESOURCE_DIMENSION = 0
	D3D12_RESOURCE_DIMENSION_BUFFER    D3D12_RESOURCE_DIMENSION = 1
	D3D12_RESOURCE_DIMENSION_TEXTURE1D D3D12_RESOURCE_DIMENSION = 2
	D3D12_RESOURCE_DIMENSION_TEXTURE2D D3D12_RESOURCE_DIMENSION = 3
	D3D12_RESOURCE_DIMENSION_TEXTURE3D D3D12_RESOURCE_DIMENSION = 4
)

// D3D12_TEXTURE_LAYOUT specifies the texture layout options.
type D3D12_TEXTURE_LAYOUT uint32

// Texture layout constants.
const (
	D3D12_TEXTURE_LAYOUT_UNKNOWN                D3D12_TEXTURE_LAYOUT = 0
	D3D12_TEXTURE_LAYOUT_ROW_MAJOR              D3D12_TEXTURE_LAYOUT = 1
	D3D12_TEXTURE_LAYOUT_64KB_UNDEFINED_SWIZZLE D3D12_TEXTURE_LAYOUT = 2
	D3D12_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE  D3D12_TEXTURE_LAYOUT = 3
)

// D3D12_RESOURCE_FLAGS specifies resource options.
type D3D12_RESOURCE_FLAGS uint32

// Resource flag constants.
const (
	D3D12_RESOURCE_FLAG_NONE                        D3D12_RESOURCE_FLAGS = 0
	D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET         D3D12_RESOURCE_FLAGS = 1
	D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL         D3D12_RESOURCE_FLAGS = 2
	D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS      D3D12_RESOURCE_FLAGS = 4
	D3D12_RESOURCE_FLAG_DENY_SHADER_RESOURCE        D3D12_RESOURCE_FLAGS = 8
	D3D12_RESOURCE_FLAG_ALLOW_CROSS_ADAPTER         D3D12_RESOURCE_FLAGS = 16
	D3D12_RESOURCE_FLAG_ALLOW_SIMULTANEOUS_ACCESS   D3D12_RESOURCE_FLAGS = 32
	D3D12_RESOURCE_FLAG_VIDEO_DECODE_REFERENCE_ONLY D3D12_RESOURCE_FLAGS = 64
)

// D3D12_RESOURCE_STATES specifies the state of a resource.
type D3D12_RESOURCE_STATES uint32

// Resource state constants.
const (
	D3D12_RESOURCE_STATE_COMMON                            D3D12_RESOURCE_STATES = 0
	D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER        D3D12_RESOURCE_STATES = 0x1
	D3D12_RESOURCE_STATE_INDEX_BUFFER                      D3D12_RESOURCE_STATES = 0x2
	D3D12_RESOURCE_STATE_RENDER_TARGET                     D3D12_RESOURCE_STATES = 0x4
	D3D12_RESOURCE_STATE_UNORDERED_ACCESS                  D3D12_RESOURCE_STATES = 0x8
	D3D12_RESOURCE_STATE_DEPTH_WRITE                       D3D12_RESOURCE_STATES = 0x10
	D3D12_RESOURCE_STATE_DEPTH_READ                        D3D12_RESOURCE_STATES = 0x20
	D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE         D3D12_RESOURCE_STATES = 0x40
	D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE             D3D12_RESOURCE_STATES = 0x80
	D3D12_RESOURCE_STATE_STREAM_OUT                        D3D12_RESOURCE_STATES = 0x100
	D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT                 D3D12_RESOURCE_STATES = 0x200
	D3D12_RESOURCE_STATE_COPY_DEST                         D3D12_RESOURCE_STATES = 0x400
	D3D12_RESOURCE_STATE_COPY_SOURCE                       D3D12_RESOURCE_STATES = 0x800
	D3D12_RESOURCE_STATE_RESOLVE_DEST                      D3D12_RESOURCE_STATES = 0x1000
	D3D12_RESOURCE_STATE_RESOLVE_SOURCE                    D3D12_RESOURCE_STATES = 0x2000
	D3D12_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE D3D12_RESOURCE_STATES = 0x400000
	D3D12_RESOURCE_STATE_SHADING_RATE_SOURCE               D3D12_RESOURCE_STATES = 0x1000000
	D3D12_RESOURCE_STATE_GENERIC_READ                      D3D12_RESOURCE_STATES = 0x1 | 0x2 | 0x40 | 0x80 | 0x200 | 0x800
	D3D12_RESOURCE_STATE_ALL_SHADER_RESOURCE               D3D12_RESOURCE_STATES = 0x40 | 0x80
	D3D12_RESOURCE_STATE_PRESENT                           D3D12_RESOURCE_STATES = 0
	D3D12_RESOURCE_STATE_PREDICATION                       D3D12_RESOURCE_STATES = 0x200
	D3D12_RESOURCE_STATE_VIDEO_DECODE_READ                 D3D12_RESOURCE_STATES = 0x10000
	D3D12_RESOURCE_STATE_VIDEO_DECODE_WRITE                D3D12_RESOURCE_STATES = 0x20000
	D3D12_RESOURCE_STATE_VIDEO_PROCESS_READ                D3D12_RESOURCE_STATES = 0x40000
	D3D12_RESOURCE_STATE_VIDEO_PROCESS_WRITE               D3D12_RESOURCE_STATES = 0x80000
	D3D12_RESOURCE_STATE_VIDEO_ENCODE_READ                 D3D12_RESOURCE_STATES = 0x200000
	D3D12_RESOURCE_STATE_VIDEO_ENCODE_WRITE                D3D12_RESOURCE_STATES = 0x800000
)

// D3D12_RESOURCE_BARRIER_TYPE specifies the type of resource barrier.
type D3D12_RESOURCE_BARRIER_TYPE uint32

// Resource barrier type constants.
const (
	D3D12_RESOURCE_BARRIER_TYPE_TRANSITION D3D12_RESOURCE_BARRIER_TYPE = 0
	D3D12_RESOURCE_BARRIER_TYPE_ALIASING   D3D12_RESOURCE_BARRIER_TYPE = 1
	D3D12_RESOURCE_BARRIER_TYPE_UAV        D3D12_RESOURCE_BARRIER_TYPE = 2
)

// D3D12_RESOURCE_BARRIER_FLAGS specifies resource barrier flags.
type D3D12_RESOURCE_BARRIER_FLAGS uint32

// Resource barrier flag constants.
const (
	D3D12_RESOURCE_BARRIER_FLAG_NONE       D3D12_RESOURCE_BARRIER_FLAGS = 0
	D3D12_RESOURCE_BARRIER_FLAG_BEGIN_ONLY D3D12_RESOURCE_BARRIER_FLAGS = 1
	D3D12_RESOURCE_BARRIER_FLAG_END_ONLY   D3D12_RESOURCE_BARRIER_FLAGS = 2
)

// D3D12_DESCRIPTOR_HEAP_TYPE specifies the type of descriptor heap.
type D3D12_DESCRIPTOR_HEAP_TYPE uint32

// Descriptor heap type constants.
const (
	D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV D3D12_DESCRIPTOR_HEAP_TYPE = 0
	D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER     D3D12_DESCRIPTOR_HEAP_TYPE = 1
	D3D12_DESCRIPTOR_HEAP_TYPE_RTV         D3D12_DESCRIPTOR_HEAP_TYPE = 2
	D3D12_DESCRIPTOR_HEAP_TYPE_DSV         D3D12_DESCRIPTOR_HEAP_TYPE = 3
	D3D12_DESCRIPTOR_HEAP_TYPE_NUM_TYPES   D3D12_DESCRIPTOR_HEAP_TYPE = 4
)

// D3D12_DESCRIPTOR_HEAP_FLAGS specifies descriptor heap flags.
type D3D12_DESCRIPTOR_HEAP_FLAGS uint32

// Descriptor heap flag constants.
const (
	D3D12_DESCRIPTOR_HEAP_FLAG_NONE           D3D12_DESCRIPTOR_HEAP_FLAGS = 0
	D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE D3D12_DESCRIPTOR_HEAP_FLAGS = 1
)

// D3D12_ROOT_PARAMETER_TYPE specifies the type of root parameter.
type D3D12_ROOT_PARAMETER_TYPE uint32

// Root parameter type constants.
const (
	D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE D3D12_ROOT_PARAMETER_TYPE = 0
	D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS  D3D12_ROOT_PARAMETER_TYPE = 1
	D3D12_ROOT_PARAMETER_TYPE_CBV              D3D12_ROOT_PARAMETER_TYPE = 2
	D3D12_ROOT_PARAMETER_TYPE_SRV              D3D12_ROOT_PARAMETER_TYPE = 3
	D3D12_ROOT_PARAMETER_TYPE_UAV              D3D12_ROOT_PARAMETER_TYPE = 4
)

// D3D12_DESCRIPTOR_RANGE_TYPE specifies the type of descriptor range.
type D3D12_DESCRIPTOR_RANGE_TYPE uint32

// Descriptor range type constants.
const (
	D3D12_DESCRIPTOR_RANGE_TYPE_SRV     D3D12_DESCRIPTOR_RANGE_TYPE = 0
	D3D12_DESCRIPTOR_RANGE_TYPE_UAV     D3D12_DESCRIPTOR_RANGE_TYPE = 1
	D3D12_DESCRIPTOR_RANGE_TYPE_CBV     D3D12_DESCRIPTOR_RANGE_TYPE = 2
	D3D12_DESCRIPTOR_RANGE_TYPE_SAMPLER D3D12_DESCRIPTOR_RANGE_TYPE = 3
)

// D3D12_SHADER_VISIBILITY specifies shader visibility for root signature parameters.
type D3D12_SHADER_VISIBILITY uint32

// Shader visibility constants.
const (
	D3D12_SHADER_VISIBILITY_ALL           D3D12_SHADER_VISIBILITY = 0
	D3D12_SHADER_VISIBILITY_VERTEX        D3D12_SHADER_VISIBILITY = 1
	D3D12_SHADER_VISIBILITY_HULL          D3D12_SHADER_VISIBILITY = 2
	D3D12_SHADER_VISIBILITY_DOMAIN        D3D12_SHADER_VISIBILITY = 3
	D3D12_SHADER_VISIBILITY_GEOMETRY      D3D12_SHADER_VISIBILITY = 4
	D3D12_SHADER_VISIBILITY_PIXEL         D3D12_SHADER_VISIBILITY = 5
	D3D12_SHADER_VISIBILITY_AMPLIFICATION D3D12_SHADER_VISIBILITY = 6
	D3D12_SHADER_VISIBILITY_MESH          D3D12_SHADER_VISIBILITY = 7
)

// D3D12_ROOT_SIGNATURE_FLAGS specifies root signature flags.
type D3D12_ROOT_SIGNATURE_FLAGS uint32

// Root signature flag constants.
const (
	D3D12_ROOT_SIGNATURE_FLAG_NONE                                  D3D12_ROOT_SIGNATURE_FLAGS = 0
	D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT    D3D12_ROOT_SIGNATURE_FLAGS = 0x1
	D3D12_ROOT_SIGNATURE_FLAG_DENY_VERTEX_SHADER_ROOT_ACCESS        D3D12_ROOT_SIGNATURE_FLAGS = 0x2
	D3D12_ROOT_SIGNATURE_FLAG_DENY_HULL_SHADER_ROOT_ACCESS          D3D12_ROOT_SIGNATURE_FLAGS = 0x4
	D3D12_ROOT_SIGNATURE_FLAG_DENY_DOMAIN_SHADER_ROOT_ACCESS        D3D12_ROOT_SIGNATURE_FLAGS = 0x8
	D3D12_ROOT_SIGNATURE_FLAG_DENY_GEOMETRY_SHADER_ROOT_ACCESS      D3D12_ROOT_SIGNATURE_FLAGS = 0x10
	D3D12_ROOT_SIGNATURE_FLAG_DENY_PIXEL_SHADER_ROOT_ACCESS         D3D12_ROOT_SIGNATURE_FLAGS = 0x20
	D3D12_ROOT_SIGNATURE_FLAG_ALLOW_STREAM_OUTPUT                   D3D12_ROOT_SIGNATURE_FLAGS = 0x40
	D3D12_ROOT_SIGNATURE_FLAG_LOCAL_ROOT_SIGNATURE                  D3D12_ROOT_SIGNATURE_FLAGS = 0x80
	D3D12_ROOT_SIGNATURE_FLAG_DENY_AMPLIFICATION_SHADER_ROOT_ACCESS D3D12_ROOT_SIGNATURE_FLAGS = 0x100
	D3D12_ROOT_SIGNATURE_FLAG_DENY_MESH_SHADER_ROOT_ACCESS          D3D12_ROOT_SIGNATURE_FLAGS = 0x200
	D3D12_ROOT_SIGNATURE_FLAG_CBV_SRV_UAV_HEAP_DIRECTLY_INDEXED     D3D12_ROOT_SIGNATURE_FLAGS = 0x400
	D3D12_ROOT_SIGNATURE_FLAG_SAMPLER_HEAP_DIRECTLY_INDEXED         D3D12_ROOT_SIGNATURE_FLAGS = 0x800
)

// D3D12_STATIC_SAMPLER_DESC_FLAGS specifies static sampler flags.
type D3D12_STATIC_SAMPLER_DESC_FLAGS uint32

// Static sampler flag constants.
const (
	D3D12_STATIC_SAMPLER_FLAG_NONE                           D3D12_STATIC_SAMPLER_DESC_FLAGS = 0
	D3D12_STATIC_SAMPLER_FLAG_BORDER_COLOR_TRANSPARENT_BLACK D3D12_STATIC_SAMPLER_DESC_FLAGS = 1
)

// D3D12_FENCE_FLAGS specifies fence flags.
type D3D12_FENCE_FLAGS uint32

// Fence flag constants.
const (
	D3D12_FENCE_FLAG_NONE                 D3D12_FENCE_FLAGS = 0
	D3D12_FENCE_FLAG_SHARED               D3D12_FENCE_FLAGS = 1
	D3D12_FENCE_FLAG_SHARED_CROSS_ADAPTER D3D12_FENCE_FLAGS = 2
	D3D12_FENCE_FLAG_NON_MONITORED        D3D12_FENCE_FLAGS = 4
)

// D3D12_PRIMITIVE_TOPOLOGY_TYPE specifies primitive topology type.
type D3D12_PRIMITIVE_TOPOLOGY_TYPE uint32

// Primitive topology type constants.
const (
	D3D12_PRIMITIVE_TOPOLOGY_TYPE_UNDEFINED D3D12_PRIMITIVE_TOPOLOGY_TYPE = 0
	D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT     D3D12_PRIMITIVE_TOPOLOGY_TYPE = 1
	D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE      D3D12_PRIMITIVE_TOPOLOGY_TYPE = 2
	D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE  D3D12_PRIMITIVE_TOPOLOGY_TYPE = 3
	D3D12_PRIMITIVE_TOPOLOGY_TYPE_PATCH     D3D12_PRIMITIVE_TOPOLOGY_TYPE = 4
)

// D3D_PRIMITIVE_TOPOLOGY specifies primitive topology.
type D3D_PRIMITIVE_TOPOLOGY uint32

// Primitive topology constants.
const (
	D3D_PRIMITIVE_TOPOLOGY_UNDEFINED         D3D_PRIMITIVE_TOPOLOGY = 0
	D3D_PRIMITIVE_TOPOLOGY_POINTLIST         D3D_PRIMITIVE_TOPOLOGY = 1
	D3D_PRIMITIVE_TOPOLOGY_LINELIST          D3D_PRIMITIVE_TOPOLOGY = 2
	D3D_PRIMITIVE_TOPOLOGY_LINESTRIP         D3D_PRIMITIVE_TOPOLOGY = 3
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST      D3D_PRIMITIVE_TOPOLOGY = 4
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP     D3D_PRIMITIVE_TOPOLOGY = 5
	D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ      D3D_PRIMITIVE_TOPOLOGY = 10
	D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ     D3D_PRIMITIVE_TOPOLOGY = 11
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ  D3D_PRIMITIVE_TOPOLOGY = 12
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ D3D_PRIMITIVE_TOPOLOGY = 13
)

// D3D12_INPUT_CLASSIFICATION specifies input slot classification.
type D3D12_INPUT_CLASSIFICATION uint32

// Input classification constants.
const (
	D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA   D3D12_INPUT_CLASSIFICATION = 0
	D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA D3D12_INPUT_CLASSIFICATION = 1
)

// D3D12_FILL_MODE specifies the fill mode.
type D3D12_FILL_MODE uint32

// Fill mode constants.
const (
	D3D12_FILL_MODE_WIREFRAME D3D12_FILL_MODE = 2
	D3D12_FILL_MODE_SOLID     D3D12_FILL_MODE = 3
)

// D3D12_CULL_MODE specifies the cull mode.
type D3D12_CULL_MODE uint32

// Cull mode constants.
const (
	D3D12_CULL_MODE_NONE  D3D12_CULL_MODE = 1
	D3D12_CULL_MODE_FRONT D3D12_CULL_MODE = 2
	D3D12_CULL_MODE_BACK  D3D12_CULL_MODE = 3
)

// D3D12_COMPARISON_FUNC specifies the comparison function.
type D3D12_COMPARISON_FUNC uint32

// Comparison function constants.
const (
	D3D12_COMPARISON_FUNC_NEVER         D3D12_COMPARISON_FUNC = 1
	D3D12_COMPARISON_FUNC_LESS          D3D12_COMPARISON_FUNC = 2
	D3D12_COMPARISON_FUNC_EQUAL         D3D12_COMPARISON_FUNC = 3
	D3D12_COMPARISON_FUNC_LESS_EQUAL    D3D12_COMPARISON_FUNC = 4
	D3D12_COMPARISON_FUNC_GREATER       D3D12_COMPARISON_FUNC = 5
	D3D12_COMPARISON_FUNC_NOT_EQUAL     D3D12_COMPARISON_FUNC = 6
	D3D12_COMPARISON_FUNC_GREATER_EQUAL D3D12_COMPARISON_FUNC = 7
	D3D12_COMPARISON_FUNC_ALWAYS        D3D12_COMPARISON_FUNC = 8
)

// D3D12_DEPTH_WRITE_MASK specifies depth write mask.
type D3D12_DEPTH_WRITE_MASK uint32

// Depth write mask constants.
const (
	D3D12_DEPTH_WRITE_MASK_ZERO D3D12_DEPTH_WRITE_MASK = 0
	D3D12_DEPTH_WRITE_MASK_ALL  D3D12_DEPTH_WRITE_MASK = 1
)

// D3D12_STENCIL_OP specifies the stencil operation.
type D3D12_STENCIL_OP uint32

// Stencil operation constants.
const (
	D3D12_STENCIL_OP_KEEP     D3D12_STENCIL_OP = 1
	D3D12_STENCIL_OP_ZERO     D3D12_STENCIL_OP = 2
	D3D12_STENCIL_OP_REPLACE  D3D12_STENCIL_OP = 3
	D3D12_STENCIL_OP_INCR_SAT D3D12_STENCIL_OP = 4
	D3D12_STENCIL_OP_DECR_SAT D3D12_STENCIL_OP = 5
	D3D12_STENCIL_OP_INVERT   D3D12_STENCIL_OP = 6
	D3D12_STENCIL_OP_INCR     D3D12_STENCIL_OP = 7
	D3D12_STENCIL_OP_DECR     D3D12_STENCIL_OP = 8
)

// D3D12_BLEND specifies blend factors.
type D3D12_BLEND uint32

// Blend factor constants.
const (
	D3D12_BLEND_ZERO             D3D12_BLEND = 1
	D3D12_BLEND_ONE              D3D12_BLEND = 2
	D3D12_BLEND_SRC_COLOR        D3D12_BLEND = 3
	D3D12_BLEND_INV_SRC_COLOR    D3D12_BLEND = 4
	D3D12_BLEND_SRC_ALPHA        D3D12_BLEND = 5
	D3D12_BLEND_INV_SRC_ALPHA    D3D12_BLEND = 6
	D3D12_BLEND_DEST_ALPHA       D3D12_BLEND = 7
	D3D12_BLEND_INV_DEST_ALPHA   D3D12_BLEND = 8
	D3D12_BLEND_DEST_COLOR       D3D12_BLEND = 9
	D3D12_BLEND_INV_DEST_COLOR   D3D12_BLEND = 10
	D3D12_BLEND_SRC_ALPHA_SAT    D3D12_BLEND = 11
	D3D12_BLEND_BLEND_FACTOR     D3D12_BLEND = 14
	D3D12_BLEND_INV_BLEND_FACTOR D3D12_BLEND = 15
	D3D12_BLEND_SRC1_COLOR       D3D12_BLEND = 16
	D3D12_BLEND_INV_SRC1_COLOR   D3D12_BLEND = 17
	D3D12_BLEND_SRC1_ALPHA       D3D12_BLEND = 18
	D3D12_BLEND_INV_SRC1_ALPHA   D3D12_BLEND = 19
)

// D3D12_BLEND_OP specifies the blend operation.
type D3D12_BLEND_OP uint32

// Blend operation constants.
const (
	D3D12_BLEND_OP_ADD          D3D12_BLEND_OP = 1
	D3D12_BLEND_OP_SUBTRACT     D3D12_BLEND_OP = 2
	D3D12_BLEND_OP_REV_SUBTRACT D3D12_BLEND_OP = 3
	D3D12_BLEND_OP_MIN          D3D12_BLEND_OP = 4
	D3D12_BLEND_OP_MAX          D3D12_BLEND_OP = 5
)

// D3D12_LOGIC_OP specifies the logical operation.
type D3D12_LOGIC_OP uint32

// Logic operation constants.
const (
	D3D12_LOGIC_OP_CLEAR         D3D12_LOGIC_OP = 0
	D3D12_LOGIC_OP_SET           D3D12_LOGIC_OP = 1
	D3D12_LOGIC_OP_COPY          D3D12_LOGIC_OP = 2
	D3D12_LOGIC_OP_COPY_INVERTED D3D12_LOGIC_OP = 3
	D3D12_LOGIC_OP_NOOP          D3D12_LOGIC_OP = 4
	D3D12_LOGIC_OP_INVERT        D3D12_LOGIC_OP = 5
	D3D12_LOGIC_OP_AND           D3D12_LOGIC_OP = 6
	D3D12_LOGIC_OP_NAND          D3D12_LOGIC_OP = 7
	D3D12_LOGIC_OP_OR            D3D12_LOGIC_OP = 8
	D3D12_LOGIC_OP_NOR           D3D12_LOGIC_OP = 9
	D3D12_LOGIC_OP_XOR           D3D12_LOGIC_OP = 10
	D3D12_LOGIC_OP_EQUIV         D3D12_LOGIC_OP = 11
	D3D12_LOGIC_OP_AND_REVERSE   D3D12_LOGIC_OP = 12
	D3D12_LOGIC_OP_AND_INVERTED  D3D12_LOGIC_OP = 13
	D3D12_LOGIC_OP_OR_REVERSE    D3D12_LOGIC_OP = 14
	D3D12_LOGIC_OP_OR_INVERTED   D3D12_LOGIC_OP = 15
)

// D3D12_COLOR_WRITE_ENABLE specifies color write enable flags.
type D3D12_COLOR_WRITE_ENABLE uint8

// Color write enable constants.
const (
	D3D12_COLOR_WRITE_ENABLE_RED   D3D12_COLOR_WRITE_ENABLE = 1
	D3D12_COLOR_WRITE_ENABLE_GREEN D3D12_COLOR_WRITE_ENABLE = 2
	D3D12_COLOR_WRITE_ENABLE_BLUE  D3D12_COLOR_WRITE_ENABLE = 4
	D3D12_COLOR_WRITE_ENABLE_ALPHA D3D12_COLOR_WRITE_ENABLE = 8
	D3D12_COLOR_WRITE_ENABLE_ALL   D3D12_COLOR_WRITE_ENABLE = 0xF
)

// D3D12_FILTER specifies filtering options.
type D3D12_FILTER uint32

// Filter constants.
const (
	D3D12_FILTER_MIN_MAG_MIP_POINT                          D3D12_FILTER = 0
	D3D12_FILTER_MIN_MAG_POINT_MIP_LINEAR                   D3D12_FILTER = 0x1
	D3D12_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT             D3D12_FILTER = 0x4
	D3D12_FILTER_MIN_POINT_MAG_MIP_LINEAR                   D3D12_FILTER = 0x5
	D3D12_FILTER_MIN_LINEAR_MAG_MIP_POINT                   D3D12_FILTER = 0x10
	D3D12_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR            D3D12_FILTER = 0x11
	D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT                   D3D12_FILTER = 0x14
	D3D12_FILTER_MIN_MAG_MIP_LINEAR                         D3D12_FILTER = 0x15
	D3D12_FILTER_ANISOTROPIC                                D3D12_FILTER = 0x55
	D3D12_FILTER_COMPARISON_MIN_MAG_MIP_POINT               D3D12_FILTER = 0x80
	D3D12_FILTER_COMPARISON_MIN_MAG_POINT_MIP_LINEAR        D3D12_FILTER = 0x81
	D3D12_FILTER_COMPARISON_MIN_POINT_MAG_LINEAR_MIP_POINT  D3D12_FILTER = 0x84
	D3D12_FILTER_COMPARISON_MIN_POINT_MAG_MIP_LINEAR        D3D12_FILTER = 0x85
	D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_MIP_POINT        D3D12_FILTER = 0x90
	D3D12_FILTER_COMPARISON_MIN_LINEAR_MAG_POINT_MIP_LINEAR D3D12_FILTER = 0x91
	D3D12_FILTER_COMPARISON_MIN_MAG_LINEAR_MIP_POINT        D3D12_FILTER = 0x94
	D3D12_FILTER_COMPARISON_MIN_MAG_MIP_LINEAR              D3D12_FILTER = 0x95
	D3D12_FILTER_COMPARISON_ANISOTROPIC                     D3D12_FILTER = 0xD5
)

// D3D12_TEXTURE_ADDRESS_MODE specifies texture address mode.
type D3D12_TEXTURE_ADDRESS_MODE uint32

// Texture address mode constants.
const (
	D3D12_TEXTURE_ADDRESS_MODE_WRAP        D3D12_TEXTURE_ADDRESS_MODE = 1
	D3D12_TEXTURE_ADDRESS_MODE_MIRROR      D3D12_TEXTURE_ADDRESS_MODE = 2
	D3D12_TEXTURE_ADDRESS_MODE_CLAMP       D3D12_TEXTURE_ADDRESS_MODE = 3
	D3D12_TEXTURE_ADDRESS_MODE_BORDER      D3D12_TEXTURE_ADDRESS_MODE = 4
	D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE D3D12_TEXTURE_ADDRESS_MODE = 5
)

// D3D12_STATIC_BORDER_COLOR specifies static border color.
type D3D12_STATIC_BORDER_COLOR uint32

// Static border color constants.
const (
	D3D12_STATIC_BORDER_COLOR_TRANSPARENT_BLACK D3D12_STATIC_BORDER_COLOR = 0
	D3D12_STATIC_BORDER_COLOR_OPAQUE_BLACK      D3D12_STATIC_BORDER_COLOR = 1
	D3D12_STATIC_BORDER_COLOR_OPAQUE_WHITE      D3D12_STATIC_BORDER_COLOR = 2
)

// D3D12_QUERY_HEAP_TYPE specifies query heap types.
type D3D12_QUERY_HEAP_TYPE uint32

// Query heap type constants.
const (
	D3D12_QUERY_HEAP_TYPE_OCCLUSION               D3D12_QUERY_HEAP_TYPE = 0
	D3D12_QUERY_HEAP_TYPE_TIMESTAMP               D3D12_QUERY_HEAP_TYPE = 1
	D3D12_QUERY_HEAP_TYPE_PIPELINE_STATISTICS     D3D12_QUERY_HEAP_TYPE = 2
	D3D12_QUERY_HEAP_TYPE_SO_STATISTICS           D3D12_QUERY_HEAP_TYPE = 3
	D3D12_QUERY_HEAP_TYPE_VIDEO_DECODE_STATISTICS D3D12_QUERY_HEAP_TYPE = 4
	D3D12_QUERY_HEAP_TYPE_COPY_QUEUE_TIMESTAMP    D3D12_QUERY_HEAP_TYPE = 5
)

// D3D12_QUERY_TYPE specifies query types.
type D3D12_QUERY_TYPE uint32

// Query type constants.
const (
	D3D12_QUERY_TYPE_OCCLUSION               D3D12_QUERY_TYPE = 0
	D3D12_QUERY_TYPE_BINARY_OCCLUSION        D3D12_QUERY_TYPE = 1
	D3D12_QUERY_TYPE_TIMESTAMP               D3D12_QUERY_TYPE = 2
	D3D12_QUERY_TYPE_PIPELINE_STATISTICS     D3D12_QUERY_TYPE = 3
	D3D12_QUERY_TYPE_SO_STATISTICS_STREAM0   D3D12_QUERY_TYPE = 4
	D3D12_QUERY_TYPE_SO_STATISTICS_STREAM1   D3D12_QUERY_TYPE = 5
	D3D12_QUERY_TYPE_SO_STATISTICS_STREAM2   D3D12_QUERY_TYPE = 6
	D3D12_QUERY_TYPE_SO_STATISTICS_STREAM3   D3D12_QUERY_TYPE = 7
	D3D12_QUERY_TYPE_VIDEO_DECODE_STATISTICS D3D12_QUERY_TYPE = 8
)

// D3D12_PREDICATION_OP specifies predication operation.
type D3D12_PREDICATION_OP uint32

// Predication operation constants.
const (
	D3D12_PREDICATION_OP_EQUAL_ZERO     D3D12_PREDICATION_OP = 0
	D3D12_PREDICATION_OP_NOT_EQUAL_ZERO D3D12_PREDICATION_OP = 1
)

// D3D12_CLEAR_FLAGS specifies clear flags.
type D3D12_CLEAR_FLAGS uint32

// Clear flag constants.
const (
	D3D12_CLEAR_FLAG_DEPTH   D3D12_CLEAR_FLAGS = 0x1
	D3D12_CLEAR_FLAG_STENCIL D3D12_CLEAR_FLAGS = 0x2
)

// D3D12_INDEX_BUFFER_STRIP_CUT_VALUE specifies index buffer strip cut value.
type D3D12_INDEX_BUFFER_STRIP_CUT_VALUE uint32

// Index buffer strip cut value constants.
const (
	D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_DISABLED   D3D12_INDEX_BUFFER_STRIP_CUT_VALUE = 0
	D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFF     D3D12_INDEX_BUFFER_STRIP_CUT_VALUE = 1
	D3D12_INDEX_BUFFER_STRIP_CUT_VALUE_0xFFFFFFFF D3D12_INDEX_BUFFER_STRIP_CUT_VALUE = 2
)

// D3D12_CONSERVATIVE_RASTERIZATION_MODE specifies conservative rasterization mode.
type D3D12_CONSERVATIVE_RASTERIZATION_MODE uint32

// Conservative rasterization mode constants.
const (
	D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF D3D12_CONSERVATIVE_RASTERIZATION_MODE = 0
	D3D12_CONSERVATIVE_RASTERIZATION_MODE_ON  D3D12_CONSERVATIVE_RASTERIZATION_MODE = 1
)

// D3D12_SRV_DIMENSION specifies shader resource view dimension.
type D3D12_SRV_DIMENSION uint32

// SRV dimension constants.
const (
	D3D12_SRV_DIMENSION_UNKNOWN                           D3D12_SRV_DIMENSION = 0
	D3D12_SRV_DIMENSION_BUFFER                            D3D12_SRV_DIMENSION = 1
	D3D12_SRV_DIMENSION_TEXTURE1D                         D3D12_SRV_DIMENSION = 2
	D3D12_SRV_DIMENSION_TEXTURE1DARRAY                    D3D12_SRV_DIMENSION = 3
	D3D12_SRV_DIMENSION_TEXTURE2D                         D3D12_SRV_DIMENSION = 4
	D3D12_SRV_DIMENSION_TEXTURE2DARRAY                    D3D12_SRV_DIMENSION = 5
	D3D12_SRV_DIMENSION_TEXTURE2DMS                       D3D12_SRV_DIMENSION = 6
	D3D12_SRV_DIMENSION_TEXTURE2DMSARRAY                  D3D12_SRV_DIMENSION = 7
	D3D12_SRV_DIMENSION_TEXTURE3D                         D3D12_SRV_DIMENSION = 8
	D3D12_SRV_DIMENSION_TEXTURECUBE                       D3D12_SRV_DIMENSION = 9
	D3D12_SRV_DIMENSION_TEXTURECUBEARRAY                  D3D12_SRV_DIMENSION = 10
	D3D12_SRV_DIMENSION_RAYTRACING_ACCELERATION_STRUCTURE D3D12_SRV_DIMENSION = 11
)

// D3D12_UAV_DIMENSION specifies unordered access view dimension.
type D3D12_UAV_DIMENSION uint32

// UAV dimension constants.
const (
	D3D12_UAV_DIMENSION_UNKNOWN        D3D12_UAV_DIMENSION = 0
	D3D12_UAV_DIMENSION_BUFFER         D3D12_UAV_DIMENSION = 1
	D3D12_UAV_DIMENSION_TEXTURE1D      D3D12_UAV_DIMENSION = 2
	D3D12_UAV_DIMENSION_TEXTURE1DARRAY D3D12_UAV_DIMENSION = 3
	D3D12_UAV_DIMENSION_TEXTURE2D      D3D12_UAV_DIMENSION = 4
	D3D12_UAV_DIMENSION_TEXTURE2DARRAY D3D12_UAV_DIMENSION = 5
	D3D12_UAV_DIMENSION_TEXTURE3D      D3D12_UAV_DIMENSION = 8
)

// D3D12_RTV_DIMENSION specifies render target view dimension.
type D3D12_RTV_DIMENSION uint32

// RTV dimension constants.
const (
	D3D12_RTV_DIMENSION_UNKNOWN          D3D12_RTV_DIMENSION = 0
	D3D12_RTV_DIMENSION_BUFFER           D3D12_RTV_DIMENSION = 1
	D3D12_RTV_DIMENSION_TEXTURE1D        D3D12_RTV_DIMENSION = 2
	D3D12_RTV_DIMENSION_TEXTURE1DARRAY   D3D12_RTV_DIMENSION = 3
	D3D12_RTV_DIMENSION_TEXTURE2D        D3D12_RTV_DIMENSION = 4
	D3D12_RTV_DIMENSION_TEXTURE2DARRAY   D3D12_RTV_DIMENSION = 5
	D3D12_RTV_DIMENSION_TEXTURE2DMS      D3D12_RTV_DIMENSION = 6
	D3D12_RTV_DIMENSION_TEXTURE2DMSARRAY D3D12_RTV_DIMENSION = 7
	D3D12_RTV_DIMENSION_TEXTURE3D        D3D12_RTV_DIMENSION = 8
)

// D3D12_DSV_DIMENSION specifies depth stencil view dimension.
type D3D12_DSV_DIMENSION uint32

// DSV dimension constants.
const (
	D3D12_DSV_DIMENSION_UNKNOWN          D3D12_DSV_DIMENSION = 0
	D3D12_DSV_DIMENSION_TEXTURE1D        D3D12_DSV_DIMENSION = 1
	D3D12_DSV_DIMENSION_TEXTURE1DARRAY   D3D12_DSV_DIMENSION = 2
	D3D12_DSV_DIMENSION_TEXTURE2D        D3D12_DSV_DIMENSION = 3
	D3D12_DSV_DIMENSION_TEXTURE2DARRAY   D3D12_DSV_DIMENSION = 4
	D3D12_DSV_DIMENSION_TEXTURE2DMS      D3D12_DSV_DIMENSION = 5
	D3D12_DSV_DIMENSION_TEXTURE2DMSARRAY D3D12_DSV_DIMENSION = 6
)

// D3D12_DSV_FLAGS specifies depth stencil view flags.
type D3D12_DSV_FLAGS uint32

// DSV flag constants.
const (
	D3D12_DSV_FLAG_NONE              D3D12_DSV_FLAGS = 0
	D3D12_DSV_FLAG_READ_ONLY_DEPTH   D3D12_DSV_FLAGS = 0x1
	D3D12_DSV_FLAG_READ_ONLY_STENCIL D3D12_DSV_FLAGS = 0x2
)

// D3D12_INDIRECT_ARGUMENT_TYPE specifies indirect argument type.
type D3D12_INDIRECT_ARGUMENT_TYPE uint32

// Indirect argument type constants.
const (
	D3D12_INDIRECT_ARGUMENT_TYPE_DRAW                  D3D12_INDIRECT_ARGUMENT_TYPE = 0
	D3D12_INDIRECT_ARGUMENT_TYPE_DRAW_INDEXED          D3D12_INDIRECT_ARGUMENT_TYPE = 1
	D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH              D3D12_INDIRECT_ARGUMENT_TYPE = 2
	D3D12_INDIRECT_ARGUMENT_TYPE_VERTEX_BUFFER_VIEW    D3D12_INDIRECT_ARGUMENT_TYPE = 3
	D3D12_INDIRECT_ARGUMENT_TYPE_INDEX_BUFFER_VIEW     D3D12_INDIRECT_ARGUMENT_TYPE = 4
	D3D12_INDIRECT_ARGUMENT_TYPE_CONSTANT              D3D12_INDIRECT_ARGUMENT_TYPE = 5
	D3D12_INDIRECT_ARGUMENT_TYPE_CONSTANT_BUFFER_VIEW  D3D12_INDIRECT_ARGUMENT_TYPE = 6
	D3D12_INDIRECT_ARGUMENT_TYPE_SHADER_RESOURCE_VIEW  D3D12_INDIRECT_ARGUMENT_TYPE = 7
	D3D12_INDIRECT_ARGUMENT_TYPE_UNORDERED_ACCESS_VIEW D3D12_INDIRECT_ARGUMENT_TYPE = 8
	D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH_RAYS         D3D12_INDIRECT_ARGUMENT_TYPE = 9
	D3D12_INDIRECT_ARGUMENT_TYPE_DISPATCH_MESH         D3D12_INDIRECT_ARGUMENT_TYPE = 10
)

// D3D12_PIPELINE_STATE_FLAGS specifies pipeline state flags.
type D3D12_PIPELINE_STATE_FLAGS uint32

// Pipeline state flag constants.
const (
	D3D12_PIPELINE_STATE_FLAG_NONE       D3D12_PIPELINE_STATE_FLAGS = 0
	D3D12_PIPELINE_STATE_FLAG_TOOL_DEBUG D3D12_PIPELINE_STATE_FLAGS = 0x1
)

// D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE specifies render pass beginning access type.
type D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE uint32

// Render pass beginning access type constants.
const (
	D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE_DISCARD   D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE = 0
	D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE_PRESERVE  D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE = 1
	D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE_CLEAR     D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE = 2
	D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE_NO_ACCESS D3D12_RENDER_PASS_BEGINNING_ACCESS_TYPE = 3
)

// D3D12_RENDER_PASS_ENDING_ACCESS_TYPE specifies render pass ending access type.
type D3D12_RENDER_PASS_ENDING_ACCESS_TYPE uint32

// Render pass ending access type constants.
const (
	D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_DISCARD   D3D12_RENDER_PASS_ENDING_ACCESS_TYPE = 0
	D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_PRESERVE  D3D12_RENDER_PASS_ENDING_ACCESS_TYPE = 1
	D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_RESOLVE   D3D12_RENDER_PASS_ENDING_ACCESS_TYPE = 2
	D3D12_RENDER_PASS_ENDING_ACCESS_TYPE_NO_ACCESS D3D12_RENDER_PASS_ENDING_ACCESS_TYPE = 3
)

// D3D12_RENDER_PASS_FLAGS specifies render pass flags.
type D3D12_RENDER_PASS_FLAGS uint32

// Render pass flag constants.
const (
	D3D12_RENDER_PASS_FLAG_NONE             D3D12_RENDER_PASS_FLAGS = 0
	D3D12_RENDER_PASS_FLAG_ALLOW_UAV_WRITES D3D12_RENDER_PASS_FLAGS = 0x1
	D3D12_RENDER_PASS_FLAG_SUSPENDING_PASS  D3D12_RENDER_PASS_FLAGS = 0x2
	D3D12_RENDER_PASS_FLAG_RESUMING_PASS    D3D12_RENDER_PASS_FLAGS = 0x4
)

// DXGI_FORMAT specifies the DXGI format.
// This is a shared type between DXGI and D3D12.
type DXGI_FORMAT uint32

// DXGI format constants (commonly used subset).
const (
	DXGI_FORMAT_UNKNOWN                  DXGI_FORMAT = 0
	DXGI_FORMAT_R32G32B32A32_TYPELESS    DXGI_FORMAT = 1
	DXGI_FORMAT_R32G32B32A32_FLOAT       DXGI_FORMAT = 2
	DXGI_FORMAT_R32G32B32A32_UINT        DXGI_FORMAT = 3
	DXGI_FORMAT_R32G32B32A32_SINT        DXGI_FORMAT = 4
	DXGI_FORMAT_R32G32B32_TYPELESS       DXGI_FORMAT = 5
	DXGI_FORMAT_R32G32B32_FLOAT          DXGI_FORMAT = 6
	DXGI_FORMAT_R32G32B32_UINT           DXGI_FORMAT = 7
	DXGI_FORMAT_R32G32B32_SINT           DXGI_FORMAT = 8
	DXGI_FORMAT_R16G16B16A16_TYPELESS    DXGI_FORMAT = 9
	DXGI_FORMAT_R16G16B16A16_FLOAT       DXGI_FORMAT = 10
	DXGI_FORMAT_R16G16B16A16_UNORM       DXGI_FORMAT = 11
	DXGI_FORMAT_R16G16B16A16_UINT        DXGI_FORMAT = 12
	DXGI_FORMAT_R16G16B16A16_SNORM       DXGI_FORMAT = 13
	DXGI_FORMAT_R16G16B16A16_SINT        DXGI_FORMAT = 14
	DXGI_FORMAT_R32G32_TYPELESS          DXGI_FORMAT = 15
	DXGI_FORMAT_R32G32_FLOAT             DXGI_FORMAT = 16
	DXGI_FORMAT_R32G32_UINT              DXGI_FORMAT = 17
	DXGI_FORMAT_R32G32_SINT              DXGI_FORMAT = 18
	DXGI_FORMAT_R10G10B10A2_TYPELESS     DXGI_FORMAT = 23
	DXGI_FORMAT_R10G10B10A2_UNORM        DXGI_FORMAT = 24
	DXGI_FORMAT_R10G10B10A2_UINT         DXGI_FORMAT = 25
	DXGI_FORMAT_R11G11B10_FLOAT          DXGI_FORMAT = 26
	DXGI_FORMAT_R8G8B8A8_TYPELESS        DXGI_FORMAT = 27
	DXGI_FORMAT_R8G8B8A8_UNORM           DXGI_FORMAT = 28
	DXGI_FORMAT_R8G8B8A8_UNORM_SRGB      DXGI_FORMAT = 29
	DXGI_FORMAT_R8G8B8A8_UINT            DXGI_FORMAT = 30
	DXGI_FORMAT_R8G8B8A8_SNORM           DXGI_FORMAT = 31
	DXGI_FORMAT_R8G8B8A8_SINT            DXGI_FORMAT = 32
	DXGI_FORMAT_R16G16_TYPELESS          DXGI_FORMAT = 33
	DXGI_FORMAT_R16G16_FLOAT             DXGI_FORMAT = 34
	DXGI_FORMAT_R16G16_UNORM             DXGI_FORMAT = 35
	DXGI_FORMAT_R16G16_UINT              DXGI_FORMAT = 36
	DXGI_FORMAT_R16G16_SNORM             DXGI_FORMAT = 37
	DXGI_FORMAT_R16G16_SINT              DXGI_FORMAT = 38
	DXGI_FORMAT_R32_TYPELESS             DXGI_FORMAT = 39
	DXGI_FORMAT_D32_FLOAT                DXGI_FORMAT = 40
	DXGI_FORMAT_R32_FLOAT                DXGI_FORMAT = 41
	DXGI_FORMAT_R32_UINT                 DXGI_FORMAT = 42
	DXGI_FORMAT_R32_SINT                 DXGI_FORMAT = 43
	DXGI_FORMAT_R24G8_TYPELESS           DXGI_FORMAT = 44
	DXGI_FORMAT_D24_UNORM_S8_UINT        DXGI_FORMAT = 45
	DXGI_FORMAT_R24_UNORM_X8_TYPELESS    DXGI_FORMAT = 46
	DXGI_FORMAT_X24_TYPELESS_G8_UINT     DXGI_FORMAT = 47
	DXGI_FORMAT_R8G8_TYPELESS            DXGI_FORMAT = 48
	DXGI_FORMAT_R8G8_UNORM               DXGI_FORMAT = 49
	DXGI_FORMAT_R8G8_UINT                DXGI_FORMAT = 50
	DXGI_FORMAT_R8G8_SNORM               DXGI_FORMAT = 51
	DXGI_FORMAT_R8G8_SINT                DXGI_FORMAT = 52
	DXGI_FORMAT_R16_TYPELESS             DXGI_FORMAT = 53
	DXGI_FORMAT_R16_FLOAT                DXGI_FORMAT = 54
	DXGI_FORMAT_D16_UNORM                DXGI_FORMAT = 55
	DXGI_FORMAT_R16_UNORM                DXGI_FORMAT = 56
	DXGI_FORMAT_R16_UINT                 DXGI_FORMAT = 57
	DXGI_FORMAT_R16_SNORM                DXGI_FORMAT = 58
	DXGI_FORMAT_R16_SINT                 DXGI_FORMAT = 59
	DXGI_FORMAT_R8_TYPELESS              DXGI_FORMAT = 60
	DXGI_FORMAT_R8_UNORM                 DXGI_FORMAT = 61
	DXGI_FORMAT_R8_UINT                  DXGI_FORMAT = 62
	DXGI_FORMAT_R8_SNORM                 DXGI_FORMAT = 63
	DXGI_FORMAT_R8_SINT                  DXGI_FORMAT = 64
	DXGI_FORMAT_A8_UNORM                 DXGI_FORMAT = 65
	DXGI_FORMAT_R1_UNORM                 DXGI_FORMAT = 66
	DXGI_FORMAT_BC1_TYPELESS             DXGI_FORMAT = 70
	DXGI_FORMAT_BC1_UNORM                DXGI_FORMAT = 71
	DXGI_FORMAT_BC1_UNORM_SRGB           DXGI_FORMAT = 72
	DXGI_FORMAT_BC2_TYPELESS             DXGI_FORMAT = 73
	DXGI_FORMAT_BC2_UNORM                DXGI_FORMAT = 74
	DXGI_FORMAT_BC2_UNORM_SRGB           DXGI_FORMAT = 75
	DXGI_FORMAT_BC3_TYPELESS             DXGI_FORMAT = 76
	DXGI_FORMAT_BC3_UNORM                DXGI_FORMAT = 77
	DXGI_FORMAT_BC3_UNORM_SRGB           DXGI_FORMAT = 78
	DXGI_FORMAT_BC4_TYPELESS             DXGI_FORMAT = 79
	DXGI_FORMAT_BC4_UNORM                DXGI_FORMAT = 80
	DXGI_FORMAT_BC4_SNORM                DXGI_FORMAT = 81
	DXGI_FORMAT_BC5_TYPELESS             DXGI_FORMAT = 82
	DXGI_FORMAT_BC5_UNORM                DXGI_FORMAT = 83
	DXGI_FORMAT_BC5_SNORM                DXGI_FORMAT = 84
	DXGI_FORMAT_B5G6R5_UNORM             DXGI_FORMAT = 85
	DXGI_FORMAT_B5G5R5A1_UNORM           DXGI_FORMAT = 86
	DXGI_FORMAT_B8G8R8A8_UNORM           DXGI_FORMAT = 87
	DXGI_FORMAT_B8G8R8X8_UNORM           DXGI_FORMAT = 88
	DXGI_FORMAT_B8G8R8A8_TYPELESS        DXGI_FORMAT = 90
	DXGI_FORMAT_B8G8R8A8_UNORM_SRGB      DXGI_FORMAT = 91
	DXGI_FORMAT_B8G8R8X8_TYPELESS        DXGI_FORMAT = 92
	DXGI_FORMAT_B8G8R8X8_UNORM_SRGB      DXGI_FORMAT = 93
	DXGI_FORMAT_BC6H_TYPELESS            DXGI_FORMAT = 94
	DXGI_FORMAT_BC6H_UF16                DXGI_FORMAT = 95
	DXGI_FORMAT_BC6H_SF16                DXGI_FORMAT = 96
	DXGI_FORMAT_BC7_TYPELESS             DXGI_FORMAT = 97
	DXGI_FORMAT_BC7_UNORM                DXGI_FORMAT = 98
	DXGI_FORMAT_BC7_UNORM_SRGB           DXGI_FORMAT = 99
	DXGI_FORMAT_R32G8X24_TYPELESS        DXGI_FORMAT = 19
	DXGI_FORMAT_D32_FLOAT_S8X24_UINT     DXGI_FORMAT = 20
	DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS DXGI_FORMAT = 21
	DXGI_FORMAT_X32_TYPELESS_G8X24_UINT  DXGI_FORMAT = 22
)

// D3D12_ROOT_SIGNATURE_VERSION specifies root signature version.
type D3D12_ROOT_SIGNATURE_VERSION uint32

// Root signature version constants.
const (
	D3D_ROOT_SIGNATURE_VERSION_1   D3D12_ROOT_SIGNATURE_VERSION = 0x1
	D3D_ROOT_SIGNATURE_VERSION_1_0 D3D12_ROOT_SIGNATURE_VERSION = 0x1
	D3D_ROOT_SIGNATURE_VERSION_1_1 D3D12_ROOT_SIGNATURE_VERSION = 0x2
)

// D3D12 subresource constants.
const (
	D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES uint32 = 0xFFFFFFFF
)

// D3D12_FEATURE specifies the feature to query.
type D3D12_FEATURE uint32

// D3D12 feature constants.
const (
	D3D12_FEATURE_D3D12_OPTIONS                         D3D12_FEATURE = 0
	D3D12_FEATURE_ARCHITECTURE                          D3D12_FEATURE = 1
	D3D12_FEATURE_FEATURE_LEVELS                        D3D12_FEATURE = 2
	D3D12_FEATURE_FORMAT_SUPPORT                        D3D12_FEATURE = 3
	D3D12_FEATURE_MULTISAMPLE_QUALITY_LEVELS            D3D12_FEATURE = 4
	D3D12_FEATURE_FORMAT_INFO                           D3D12_FEATURE = 5
	D3D12_FEATURE_GPU_VIRTUAL_ADDRESS_SUPPORT           D3D12_FEATURE = 6
	D3D12_FEATURE_SHADER_MODEL                          D3D12_FEATURE = 7
	D3D12_FEATURE_D3D12_OPTIONS1                        D3D12_FEATURE = 8
	D3D12_FEATURE_PROTECTED_RESOURCE_SESSION_SUPPORT    D3D12_FEATURE = 10
	D3D12_FEATURE_ROOT_SIGNATURE                        D3D12_FEATURE = 12
	D3D12_FEATURE_ARCHITECTURE1                         D3D12_FEATURE = 16
	D3D12_FEATURE_D3D12_OPTIONS2                        D3D12_FEATURE = 18
	D3D12_FEATURE_SHADER_CACHE                          D3D12_FEATURE = 19
	D3D12_FEATURE_COMMAND_QUEUE_PRIORITY                D3D12_FEATURE = 20
	D3D12_FEATURE_D3D12_OPTIONS3                        D3D12_FEATURE = 21
	D3D12_FEATURE_EXISTING_HEAPS                        D3D12_FEATURE = 22
	D3D12_FEATURE_D3D12_OPTIONS4                        D3D12_FEATURE = 23
	D3D12_FEATURE_SERIALIZATION                         D3D12_FEATURE = 24
	D3D12_FEATURE_CROSS_NODE                            D3D12_FEATURE = 25
	D3D12_FEATURE_D3D12_OPTIONS5                        D3D12_FEATURE = 27
	D3D12_FEATURE_D3D12_OPTIONS6                        D3D12_FEATURE = 30
	D3D12_FEATURE_QUERY_META_COMMAND                    D3D12_FEATURE = 31
	D3D12_FEATURE_D3D12_OPTIONS7                        D3D12_FEATURE = 32
	D3D12_FEATURE_PROTECTED_RESOURCE_SESSION_TYPE_COUNT D3D12_FEATURE = 33
	D3D12_FEATURE_PROTECTED_RESOURCE_SESSION_TYPES      D3D12_FEATURE = 34
)
