// Copyright 2025 The GoGPU Authors
// SPDX-License-Identifier: MIT

//go:build windows

package dxgi

import (
	"errors"

	"github.com/gogpu/wgpu/hal/dx12/d3d12"
)

// DXGI-specific HRESULT error codes.
// These are re-exported from d3d12 package for convenience.
const (
	// DXGI success codes
	DXGI_STATUS_OCCLUDED                     = d3d12.HRESULTError(0x087A0001)
	DXGI_STATUS_CLIPPED                      = d3d12.HRESULTError(0x087A0002)
	DXGI_STATUS_NO_REDIRECTION               = d3d12.HRESULTError(0x087A0004)
	DXGI_STATUS_NO_DESKTOP_ACCESS            = d3d12.HRESULTError(0x087A0005)
	DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE = d3d12.HRESULTError(0x087A0006)
	DXGI_STATUS_MODE_CHANGED                 = d3d12.HRESULTError(0x087A0007)
	DXGI_STATUS_MODE_CHANGE_IN_PROGRESS      = d3d12.HRESULTError(0x087A0008)
	DXGI_STATUS_UNOCCLUDED                   = d3d12.HRESULTError(0x087A0009)
	DXGI_STATUS_DDA_WAS_STILL_DRAWING        = d3d12.HRESULTError(0x087A000A)
	DXGI_STATUS_PRESENT_REQUIRED             = d3d12.HRESULTError(0x087A002F)

	// DXGI error codes (re-exported from d3d12 for convenience)
	DXGI_ERROR_INVALID_CALL                  = d3d12.DXGI_ERROR_INVALID_CALL
	DXGI_ERROR_NOT_FOUND                     = d3d12.DXGI_ERROR_NOT_FOUND
	DXGI_ERROR_MORE_DATA                     = d3d12.DXGI_ERROR_MORE_DATA
	DXGI_ERROR_UNSUPPORTED                   = d3d12.DXGI_ERROR_UNSUPPORTED
	DXGI_ERROR_DEVICE_REMOVED                = d3d12.DXGI_ERROR_DEVICE_REMOVED
	DXGI_ERROR_DEVICE_HUNG                   = d3d12.DXGI_ERROR_DEVICE_HUNG
	DXGI_ERROR_DEVICE_RESET                  = d3d12.DXGI_ERROR_DEVICE_RESET
	DXGI_ERROR_WAS_STILL_DRAWING             = d3d12.DXGI_ERROR_WAS_STILL_DRAWING
	DXGI_ERROR_FRAME_STATISTICS_DISJOINT     = d3d12.DXGI_ERROR_FRAME_STATISTICS_DISJOINT
	DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE  = d3d12.DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE
	DXGI_ERROR_DRIVER_INTERNAL_ERROR         = d3d12.DXGI_ERROR_DRIVER_INTERNAL_ERROR
	DXGI_ERROR_NONEXCLUSIVE                  = d3d12.DXGI_ERROR_NONEXCLUSIVE
	DXGI_ERROR_NOT_CURRENTLY_AVAILABLE       = d3d12.DXGI_ERROR_NOT_CURRENTLY_AVAILABLE
	DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED    = d3d12.DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED
	DXGI_ERROR_REMOTE_OUTOFMEMORY            = d3d12.DXGI_ERROR_REMOTE_OUTOFMEMORY
	DXGI_ERROR_ACCESS_LOST                   = d3d12.DXGI_ERROR_ACCESS_LOST
	DXGI_ERROR_WAIT_TIMEOUT                  = d3d12.DXGI_ERROR_WAIT_TIMEOUT
	DXGI_ERROR_SESSION_DISCONNECTED          = d3d12.DXGI_ERROR_SESSION_DISCONNECTED
	DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE      = d3d12.DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE
	DXGI_ERROR_CANNOT_PROTECT_CONTENT        = d3d12.DXGI_ERROR_CANNOT_PROTECT_CONTENT
	DXGI_ERROR_ACCESS_DENIED                 = d3d12.DXGI_ERROR_ACCESS_DENIED
	DXGI_ERROR_NAME_ALREADY_EXISTS           = d3d12.DXGI_ERROR_NAME_ALREADY_EXISTS
	DXGI_ERROR_SDK_COMPONENT_MISSING         = d3d12.DXGI_ERROR_SDK_COMPONENT_MISSING
	DXGI_ERROR_NOT_CURRENT                   = d3d12.DXGI_ERROR_NOT_CURRENT
	DXGI_ERROR_HW_PROTECTION_OUTOFMEMORY     = d3d12.DXGI_ERROR_HW_PROTECTION_OUTOFMEMORY
	DXGI_ERROR_DYNAMIC_CODE_POLICY_VIOLATION = d3d12.DXGI_ERROR_DYNAMIC_CODE_POLICY_VIOLATION
	DXGI_ERROR_NON_COMPOSITED_UI             = d3d12.DXGI_ERROR_NON_COMPOSITED_UI
)

// IsDeviceRemovedError returns true if the error indicates the device was removed.
func IsDeviceRemovedError(err error) bool {
	var hr d3d12.HRESULTError
	if errors.As(err, &hr) {
		switch hr {
		case DXGI_ERROR_DEVICE_REMOVED,
			DXGI_ERROR_DEVICE_HUNG,
			DXGI_ERROR_DEVICE_RESET,
			DXGI_ERROR_DRIVER_INTERNAL_ERROR:
			return true
		}
	}
	return false
}

// IsOccluded returns true if the HRESULT indicates the window is occluded.
func IsOccluded(err error) bool {
	var hr d3d12.HRESULTError
	if errors.As(err, &hr) {
		return hr == DXGI_STATUS_OCCLUDED
	}
	return false
}

// IsModeChanged returns true if the display mode changed.
func IsModeChanged(err error) bool {
	var hr d3d12.HRESULTError
	if errors.As(err, &hr) {
		return hr == DXGI_STATUS_MODE_CHANGED || hr == DXGI_STATUS_MODE_CHANGE_IN_PROGRESS
	}
	return false
}
